app = "your-app-name"

[build]
  image = "neosmemo/memos:latest"

[env]
  MEMOS_DRIVER = "sqlite"

[[services]]
  internal_port = 5230
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443